// get-content.js
// GET endpoint: returns the latest digest, weekly roundup, and fee alerts as a single JSON response.
// Frontend calls this to display automated content generated by the scheduled functions.
//
// Note: the scheduled functions write to /tmp which is ephemeral in Netlify's Lambda environment.
// Each function invocation may start with a clean /tmp. For persistent storage across invocations,
// consider migrating to Netlify Blobs or an external store (e.g. Supabase, Upstash).

const fs = require('fs');

const FILES = {
  feedwatch: '/tmp/feedwatch-digest.json',
  regulatory: '/tmp/weekly-regulatory.json',
  feeAlerts: '/tmp/fee-alerts.json',
};

function readJson(filePath) {
  try {
    const raw = fs.readFileSync(filePath, 'utf8');
    return JSON.parse(raw);
  } catch {
    return null;
  }
}

exports.handler = async function (event) {
  if (event.httpMethod !== 'GET') {
    return { statusCode: 405, body: JSON.stringify({ error: 'Method not allowed' }) };
  }

  const feedwatch = readJson(FILES.feedwatch);
  const regulatory = readJson(FILES.regulatory);
  const feeAlerts = readJson(FILES.feeAlerts);

  const hasContent = feedwatch || regulatory || feeAlerts;

  return {
    statusCode: 200,
    headers: {
      'Content-Type': 'application/json',
      'Cache-Control': 'public, max-age=300', // 5-minute browser cache
    },
    body: JSON.stringify({
      retrievedAt: new Date().toISOString(),
      available: {
        feedwatch: !!feedwatch,
        regulatory: !!regulatory,
        feeAlerts: !!feeAlerts,
      },
      feedwatch: feedwatch ?? { message: 'No digest available yet. Runs daily at 6am ET.' },
      regulatory: regulatory ?? { message: 'No roundup available yet. Runs every Monday at 7am ET.' },
      feeAlerts: feeAlerts ?? { message: 'No fee change alerts on file. Monitor runs daily at 8am ET.' },
      _note: hasContent
        ? undefined
        : 'No generated content found. Scheduled functions write to /tmp which resets between invocations. Trigger a scheduled function manually to generate content.',
    }),
  };
};
