{
  "version": "1.0",
  "generated": "2026-02-28",
  "total": 20,
  "entries": [
    {
      "id": "FW-2026-019",
      "title": "CFTC Large Trader Reporting — New FIXML Position Message Format Live March 2025",
      "organization": "CFTC",
      "category": "Regulatory Deadline",
      "region": "US",
      "impact": "medium",
      "action_required": true,
      "impact_type": "Compliance, Reporting",
      "announced_date": "2024-04-30",
      "effective_date": "2025-03-10",
      "summary": "CFTC final rules amending Large Trader Reporting regulations for Futures and Options took effect in April 2024. CME Group began accepting new Position Message FIXML format files via SFTP on March 10, 2025. Firms must use new FIXML format including Unique Instrument Code (UIC) fields. Instrument listing with UIC data has been available via CME APIs since October 2024. Firms not yet migrated should prioritize this transition.",
      "tags": ["CFTC", "large trader reporting", "FIXML", "futures", "UIC"],
      "source_url": "https://www.cmegroup.com/notices/electronic-trading/2025/10/20251013.html"
    },
    {
      "id": "FW-2026-007",
      "title": "NYSE Port Fee Increase — MDC Co-location Connectivity (Up to 11.1%)",
      "organization": "NYSE",
      "category": "Billing Change",
      "region": "US",
      "impact": "low",
      "action_required": false,
      "impact_type": "Billing",
      "announced_date": "2025-09-25",
      "effective_date": "2025-10-01",
      "summary": "NYSE filed proposed rule change SR-NYSE-2025-37 to increase monthly recurring port fees for co-location hall connections at the MDC by up to 11.1%, based on Data PPI inflation tracking. First fee increase since 2017. Applies to NYSE, NYSE American, NYSE Arca, NYSE National, and NYSE Texas through affiliate SRO filings. Changes took effect October 2025.",
      "tags": ["NYSE", "co-location", "port fees", "MDC", "connectivity"],
      "source_url": "https://www.federalregister.gov/documents/2025/09/30/2025-18952"
    },
    {
      "id": "FW-2026-005",
      "title": "CME Globex: Variable Tick Expansion to Four Levels for S&P 500, Nasdaq-100, Russell 2000 Options",
      "organization": "CME Group",
      "category": "Spec Update",
      "region": "US",
      "impact": "medium",
      "action_required": true,
      "impact_type": "Protocol, Market Data",
      "announced_date": "2025-10-27",
      "effective_date": "2026-01-01",
      "summary": "CME Group will expand variable ticks from two levels to four levels for S&P 500, Nasdaq-100, and Russell 2000 options on CME Globex starting January 2026. Firms must cancel all Good Till Cancel (GTC) and Good Till Date (GTD) orders before the Friday prior to each product's production launch. CME Global Command Center will cancel remaining GT orders after 16:00 CT on launch Friday.",
      "tags": ["CME", "Globex", "options", "variable tick", "S&P 500"],
      "source_url": "https://www.cmegroup.com/notices/electronic-trading/2025/10/20251027a.html"
    },
    {
      "id": "FW-2026-008",
      "title": "Nasdaq PHLX Technology Migration — SQF, FIX Port Transition Period",
      "organization": "NASDAQ",
      "category": "Port Migration",
      "region": "US",
      "impact": "high",
      "action_required": true,
      "impact_type": "Connectivity, Billing",
      "announced_date": "2025-08-04",
      "effective_date": "2026-01-01",
      "summary": "Nasdaq PHLX is migrating to new technology infrastructure. During transition period (November–December 2025), members can acquire duplicate SQF Ports, SQF Purge Ports, and CTI Ports at no additional cost. New OTTO and FIX Drop Port fees apply from November 1, 2025. Legacy duplicate ports not returned by December 31, 2025 will be billed at standard rates from January 1, 2026. Members should review port inventory and return unneeded legacy ports before year-end.",
      "tags": ["NASDAQ", "PHLX", "SQF", "FIX", "OTTO"],
      "source_url": "https://www.federalregister.gov/documents/2025/08/04/2025-14674"
    },
    {
      "id": "FW-2026-009",
      "title": "FINRA 2026 Annual Regulatory Oversight Report — CAT Compliance Priorities",
      "organization": "FINRA",
      "category": "Regulatory Deadline",
      "region": "US",
      "impact": "medium",
      "action_required": true,
      "impact_type": "Compliance",
      "announced_date": "2025-12-09",
      "effective_date": "2026-01-01",
      "summary": "FINRA released its 2026 Regulatory Oversight Report emphasizing CAT (Consolidated Audit Trail) compliance as a top priority. Key findings include incomplete submission of reportable events, failure to timely repair errors, and inaccurate reporting. FINRA also highlights the SEC's February 2025 CAIS exemptive relief and pending CAT NMS Plan amendment to eliminate certain customer information reporting requirements. Firms should review CAT reporting workflows against FINRA Regulatory Notice 20-31.",
      "tags": ["FINRA", "CAT", "NMS Plan", "compliance", "CAIS"],
      "source_url": "https://www.finra.org/rules-guidance/guidance/reports/2026-finra-annual-regulatory-oversight-report"
    },
    {
      "id": "FW-2026-010",
      "title": "FINRA Rule 6830 Amendment — CAT Reporting of Bona Fide Market Making (BFMM) Locate Exception",
      "organization": "FINRA",
      "category": "Regulatory Deadline",
      "region": "US",
      "impact": "medium",
      "action_required": true,
      "impact_type": "Compliance",
      "announced_date": "2025-12-12",
      "effective_date": "2026-01-01",
      "summary": "FINRA filed SR-FINRA-2025-016 to amend Rule 6830 to require CAT reporting of reliance on the Bona Fide Market Making Locate Exception under Regulation SHO Rule 203(b)(2)(iii). Firms engaged in bona fide market making must record and report to the Central Repository when the BFMM Locate Exception is claimed on short sale orders. Effective upon filing with the SEC, December 2025.",
      "tags": ["FINRA", "CAT", "Rule 6830", "Reg SHO", "BFMM"],
      "source_url": "https://www.federalregister.gov/documents/2025/12/31/2025-24048"
    },
    {
      "id": "FW-2026-014",
      "title": "FINRA SLATE Reporting Launch — Securities Lending Transaction Data (Rule 10c-1a)",
      "organization": "FINRA",
      "category": "Regulatory Deadline",
      "region": "US",
      "impact": "high",
      "action_required": true,
      "impact_type": "Compliance, Reporting",
      "announced_date": "2025-01-24",
      "effective_date": "2026-01-02",
      "summary": "FINRA's SLATE (Securities Lending and Transparency Engine) reporting system under Rule 10c-1a launched January 2, 2026. Covered persons are required to report securities loan transaction data to SLATE. FINRA had petitioned the SEC to delay the launch date citing operational risks. Firms must ensure SLATE connectivity, mapping, and reporting workflows are operational. Published data will begin appearing within 90 days of the reporting start date.",
      "tags": ["FINRA", "SLATE", "Rule 10c-1a", "securities lending", "transparency"],
      "source_url": "https://www.finra.org/rules-guidance/rulebooks/finra-rules/6500"
    },
    {
      "id": "FW-2026-003",
      "title": "CME Globex iLink SBE Schema Update to Version 9",
      "organization": "CME Group",
      "category": "Protocol Update",
      "region": "US",
      "impact": "high",
      "action_required": true,
      "impact_type": "Protocol",
      "announced_date": "2025-11-17",
      "effective_date": "2026-01-25",
      "summary": "CME Group will update the iLink SBE (Simple Binary Encoding) schema to version 9 on January 25, 2026, to support upcoming CME Globex enhancements. New schema files support Template Extension for iLink messages. Available in New Release for customer testing. Firms must update parser implementations before the production launch date.",
      "tags": ["CME", "Globex", "iLink", "SBE", "schema"],
      "source_url": "https://www.cmegroup.com/notices/electronic-trading/2025/11/20251117.html"
    },
    {
      "id": "FW-2026-018",
      "title": "CME Globex: BrokerTec Chicago CLOB Launch — New GLink Connectivity Required",
      "organization": "CME Group",
      "category": "New Product / Connectivity",
      "region": "US",
      "impact": "low",
      "action_required": false,
      "impact_type": "Connectivity",
      "announced_date": "2025-10-06",
      "effective_date": "2026-02-01",
      "summary": "CME Group launched BrokerTec Chicago, a secondary U.S. Treasury Actives CLOB on CME Globex in Aurora, IL. A new BrokerTec Chicago GLink is available for dedicated connectivity. Discount pricing applies through December 31, 2026 (from $1,000/month October–January, then $2,500/month through year-end). Early termination fee waiver through January 31, 2026. Contact Global Account Manager to order.",
      "tags": ["CME", "BrokerTec", "US Treasury", "CLOB", "GLink"],
      "source_url": "https://www.cmegroup.com/notices/electronic-trading/2025/10/20251020.html"
    },
    {
      "id": "FW-2026-015",
      "title": "Form 13H Annual Update — Large Trader Reporting Deadline (February 17, 2026)",
      "organization": "SEC",
      "category": "Regulatory Deadline",
      "region": "US",
      "impact": "low",
      "action_required": true,
      "impact_type": "Compliance",
      "announced_date": "2026-01-01",
      "effective_date": "2026-02-17",
      "summary": "Annual update of Form 13H is due February 17, 2026, for large traders that exercised investment discretion over NMS securities in aggregate amounts equal to or greater than 2 million shares or $20 million in any calendar day, or 20 million shares or $200 million in any calendar month during 2025. Inaccurate or outdated information must be amended promptly at the end of any calendar quarter in which information becomes inaccurate.",
      "tags": ["SEC", "Form 13H", "large trader", "NMS", "annual filing"],
      "source_url": "https://www.sec.gov/forms/form-13h"
    },
    {
      "id": "FW-2026-002",
      "title": "CME Globex: 1Gbps Connections Will No Longer Support MDP 3 Multicast Market Data",
      "organization": "CME Group",
      "category": "Feed Change",
      "region": "US",
      "impact": "high",
      "action_required": true,
      "impact_type": "Connectivity, Market Data",
      "announced_date": "2025-10-13",
      "effective_date": "2026-03-01",
      "summary": "Effective March 2026, 1Gbps connections will no longer support MDP 3 multicast market data on CME Globex due to feed bandwidth regularly exceeding 1Gbps. Firms currently receiving multicast market data on 1Gbps connections must upgrade to 10Gbps. Unicast services including iLink, Drop Copy, STP, and MQ remain supported on 1Gbps.",
      "tags": ["CME", "Globex", "MDP 3.0", "multicast", "1Gbps"],
      "source_url": "https://www.cmegroup.com/notices/electronic-trading/2025/10/20251013.html"
    },
    {
      "id": "FW-2026-017",
      "title": "Nasdaq Nordic NLS Specification 1.2.10 — Valid from March 2, 2026",
      "organization": "NASDAQ",
      "category": "Spec Update",
      "region": "EU",
      "impact": "medium",
      "action_required": true,
      "impact_type": "Protocol",
      "announced_date": "2026-01-01",
      "effective_date": "2026-03-02",
      "summary": "Nasdaq Nordic will deploy updated NLS (Nordic Last Sale) protocol specification version 1.2.10 effective March 2, 2026. Firms consuming NLS data feeds from Nasdaq Nordic and Baltic markets should review the updated specification for message format changes. Updated spec documents are available on the Nasdaq INET Nordic Protocol Specifications page.",
      "tags": ["NASDAQ", "Nordic", "NLS", "protocol spec", "last sale"],
      "source_url": "https://www.nasdaq.com/solutions/inet-nordic-protocol-specifications"
    },
    {
      "id": "FW-2026-020",
      "title": "CME Globex: Implied Functionality Enabled for New Options Products (March 2026)",
      "organization": "CME Group",
      "category": "Spec Update",
      "region": "US",
      "impact": "low",
      "action_required": false,
      "impact_type": "Market Data",
      "announced_date": "2025-12-29",
      "effective_date": "2026-03-02",
      "summary": "Effective March 2, 2026 (trade date March 2), CME Group will enable implied functionality for additional futures and options listed on CME Globex. A full list of impacted options products will be provided in future Globex notices. Firms consuming CME options market data should review implied pricing handling in feed processors once the full product list is published.",
      "tags": ["CME", "Globex", "implied functionality", "options", "market data"],
      "source_url": "https://www.cmegroup.com/notices/electronic-trading/2025/12/20251229.html"
    },
    {
      "id": "FW-2026-016",
      "title": "CME Globex: Network Connectivity Update for Market Segment 74 (24/7 Trading Preparation)",
      "organization": "CME Group",
      "category": "Feed Change",
      "region": "US",
      "impact": "high",
      "action_required": true,
      "impact_type": "Connectivity, Protocol",
      "announced_date": "2025-10-20",
      "effective_date": "2026-Q1",
      "summary": "In Q1 2026, CME Group will update iLink, Drop Copy, and MDP 3.0 Production network connectivity for Market Segment 74 (tag 1300-MarketSegmentID) to prepare for 24/7 trading. Firms must review the client impact assessment for updated network connectivity information and migrate IP configurations for MSGW iLink and Drop Copy sessions for impacted products. Changes are available in New Release for testing.",
      "tags": ["CME", "Globex", "24/7 trading", "iLink", "Drop Copy"],
      "source_url": "https://www.cmegroup.com/notices/electronic-trading/2025/10/20251020.html"
    },
    {
      "id": "FW-2026-006",
      "title": "CME Globex: New Market Data Multicast Group — Channel ID 324 (Q1 2026)",
      "organization": "CME Group",
      "category": "Feed Change",
      "region": "US",
      "impact": "medium",
      "action_required": true,
      "impact_type": "Market Data, Connectivity",
      "announced_date": "2025-12-29",
      "effective_date": "2026-Q1",
      "summary": "CME Group will launch a new market data multicast group in Q1 2026 for a new futures product suite in the Equity Indices and Alternative Products asset class. The new multicast group will use Channel ID 324. A second new multicast group with Channel ID 335 is also planned for the first half of 2026. Firms should update firewall policies and network configurations proactively.",
      "tags": ["CME", "Globex", "multicast", "MDP 3.0", "channel ID"],
      "source_url": "https://www.cmegroup.com/notices/electronic-trading/2025/12/20251229.html"
    },
    {
      "id": "FW-2026-004",
      "title": "CME Globex: End-of-Life Network Equipment Replacement at Globex Hubs",
      "organization": "CME Group",
      "category": "Infrastructure Maintenance",
      "region": "US",
      "impact": "medium",
      "action_required": false,
      "impact_type": "Connectivity",
      "announced_date": "2025-10-20",
      "effective_date": "2026-04-01",
      "summary": "Starting April 2026, CME Group will replace end-of-life network equipment supporting listed derivatives connectivity at CME Globex Hubs. Copper handoffs will no longer be supported after the upgrades roll out. Customers will be notified individually in advance if their connectivity is impacted. Contact your Global Account Manager for details.",
      "tags": ["CME", "Globex", "network", "infrastructure", "copper handoff"],
      "source_url": "https://www.cmegroup.com/notices/electronic-trading/2025/10/20251020.html"
    },
    {
      "id": "FW-2026-012",
      "title": "Regulation S-P Cybersecurity Amendments — Smaller RIA Compliance Deadline",
      "organization": "SEC",
      "category": "Regulatory Deadline",
      "region": "US",
      "impact": "high",
      "action_required": true,
      "impact_type": "Compliance",
      "announced_date": "2024-05-16",
      "effective_date": "2026-06-03",
      "summary": "SEC Regulation S-P (Safeguards Rule) cybersecurity amendments require SEC-registered investment advisers with less than $1.5 billion AUM to implement written incident response programs by June 3, 2026. Requirements include investor notification obligations for covered incidents and oversight procedures for service providers. Larger RIAs (over $1.5B AUM) were required to comply from December 3, 2025.",
      "tags": ["SEC", "Regulation S-P", "cybersecurity", "RIA", "safeguards rule"],
      "source_url": "https://www.sec.gov/rules-regulations/2024/05/34-100155"
    },
    {
      "id": "FW-2026-011",
      "title": "Rule 605 NMS Plan Amendment — Expanded Execution Quality Reporting (Effective August 2026)",
      "organization": "SEC",
      "category": "Regulatory Deadline",
      "region": "US",
      "impact": "high",
      "action_required": true,
      "impact_type": "Compliance, Reporting",
      "announced_date": "2025-09-01",
      "effective_date": "2026-08-01",
      "summary": "The SEC approved amendments to the Rule 605 NMS Plan in September 2025 to reflect recently adopted Rule 605 amendments. The amended plan expands reporting scope to include larger broker-dealers in addition to market centers, modifies execution quality report content, and adds a summary execution quality report requirement. Compliance deadline is August 1, 2026. Firms should begin implementation planning now.",
      "tags": ["SEC", "Rule 605", "NMS Plan", "execution quality", "broker-dealer"],
      "source_url": "https://www.finra.org/rules-guidance/guidance/national-market-system-plans"
    },
    {
      "id": "FW-2026-013",
      "title": "CAT NMS Plan Amendment — CAIS Customer Information Reporting Elimination (Pending SEC Approval)",
      "organization": "SEC",
      "category": "Regulatory Deadline",
      "region": "US",
      "impact": "medium",
      "action_required": false,
      "impact_type": "Compliance, Reporting",
      "announced_date": "2025-03-13",
      "effective_date": "2026-TBD",
      "summary": "CAT LLC filed a proposed amendment on March 13, 2025 to eliminate CAT NMS Plan requirements for Industry Members to report customer names, addresses, and years of birth for natural and legal entity accounts. If approved by SEC, this would reduce CAIS reporting obligations significantly. SEC exemptive relief issued February 2025 provides interim relief for Designated Natural Person reporting. Monitor for SEC approval order.",
      "tags": ["CAT", "NMS Plan", "CAIS", "SEC", "customer information"],
      "source_url": "https://www.finra.org/rules-guidance/guidance/reports/2026-finra-annual-regulatory-oversight-report/cat"
    },
    {
      "id": "FW-2026-001",
      "title": "CME Globex Migration to Google Cloud — Preview Phase Launch",
      "organization": "CME Group",
      "category": "Infrastructure Migration",
      "region": "US",
      "impact": "critical",
      "action_required": true,
      "impact_type": "Connectivity, Protocol",
      "announced_date": "2025-10-27",
      "effective_date": "2026-Q2",
      "summary": "CME Group and Google Cloud announced a private Google Cloud Chicago region and co-location facility for CME Group listed derivative markets. Preview phase launches in 2026. Clients must review technical specifications and plan for iLink, Drop Copy, and MDP 3.0 IP configuration migrations.",
      "tags": ["CME", "Globex", "Google Cloud", "iLink", "MDP 3.0"],
      "source_url": "https://www.cmegroup.com/notices/electronic-trading/2025/10/20251027a.html"
    }
  ]
}
